vich_uploader:
    db_driver: orm

    mappings:
        prestationImages:
            uri_prefix: /uploads/prestations
            upload_destination: '%kernel.project_dir%/public/uploads/prestation'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            delete_on_update: true
            delete_on_remove: true

        provider:
            uri_prefix: /uploads/provider
            upload_destination: '%kernel.project_dir%/public/uploads/provider'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            delete_on_update: false
            delete_on_remove: true

        customer:
            uri_prefix: /uploads/customer
            upload_destination: '%kernel.project_dir%/public/uploads/customer'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            delete_on_update: false
            delete_on_remove: true

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
